### PR TITLE
Feature/jasenehines mycroft.sh

### PR DESCRIPTION
**Pull request by aatchison**
I fixed a typo.
I also took the liberty of adding a `mkdir -p logs` and moved the logs there. I also added them to the .gitignore. What do you think?
Could we add a kill function as well?

### CODE REVIEW

**Comment by aatchison** [comment]
Actually, It seems I cant commit a .git ignore indirectly as such. I'm a bit of a noob too hehe.

**Comment by aatchison** [comment]
NVM, it worked fine.

**Comment by jasonehines** [comment]
Nice catch on the typo. The log folder is a good idea too. I'll write a kill script up tomorrow when I have time.

**Comment by aatchison** [comment]
Cool! Thanks a lot!

**Comment by jasonehines** [comment]
If you want I can make it into a systemd and an OS X daemon? I might be able to do a windows service too; but it's been long time since I programmed anything in C#. If I do that, should it be one daemon or three? Also, should we move the logs to a mycroft folder in the system logs folder?

**Pull request merged**
